apiVersion: v1
kind: ConfigMap
metadata:
  name: "${{ values.name }}-app-config"
  labels:
    app: "${{ values.name }}-app"
data:
  # Application configuration
  APP_NAME: "FastAPI Application"
  APP_VERSION: "1.0.0"
  
  # Server configuration
  HOST: "0.0.0.0"
  PORT: "8000"
  WORKERS: "4"
  
  # Logging configuration
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  
  # CORS configuration
  CORS_ORIGINS: "https://yourdomain.com,https://www.yourdomain.com"
  CORS_ALLOW_CREDENTIALS: "true"
  
  # Rate limiting
  RATE_LIMIT_PER_MINUTE: "100"
  
  # Health check configuration
  HEALTH_CHECK_INTERVAL: "30"
  HEALTH_CHECK_TIMEOUT: "5"
  
  # Database configuration (if using external database)
  DATABASE_URL: "postgresql://user:password@postgres-service:5432/fastapi_db"
  
  # Redis configuration (if using Redis)
  REDIS_URL: "redis://redis-service:6379/0"
  
  # External API configuration
  EXTERNAL_API_BASE_URL: "https://api.external-service.com"
  EXTERNAL_API_TIMEOUT: "30" 