apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "${{ values.name }}-app-ingress"
  labels:
    app: "${{ values.name }}-app"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "api.yourdomain.com"
spec:
  tls:
  - hosts:
    - api.yourdomain.com
    secretName: "${{ values.name }}-app-tls"
  rules:
  - host: api.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: "${{ values.name }}-app-service"
            port:
              number: 80
      - path: /health
        pathType: Exact
        backend:
          service:
            name: "${{ values.name }}-app-service"
            port:
              number: 80
      - path: /metrics
        pathType: Exact
        backend:
          service:
            name: "${{ values.name }}-app-service"
            port:
              number: 80 