apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "${{ values.name }}-app-network-policy"
  labels:
    app: "${{ values.name }}-app"
spec:
  podSelector:
    matchLabels:
      app: "${{ values.name }}-app"
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from ingress controller
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8000
  # Allow traffic from same namespace
  - from:
    - podSelector:
        matchLabels:
          app: "${{ values.name }}-app"
    ports:
    - protocol: TCP
      port: 8000
  egress:
  # Allow DNS queries
  - to: []
    ports:
    - protocol: UDP
      port: 53
  # Allow HTTP/HTTPS to external APIs
  - to: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
  # Allow traffic to database (if in same cluster)
  # - to:
  #   - podSelector:
  #       matchLabels:
  #         app: postgres
  #   ports:
  #   - protocol: TCP
  #     port: 5432