apiVersion: v1
kind: Service
metadata:
  name: "${{ values.name }}-app-service"
  labels:
    app: "${{ values.name }}-app"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: "${{ values.name }}-app"
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: "${{ values.name }}-app-headless"
  labels:
    app: "${{ values.name }}-app"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: "${{ values.name }}-app" 